### ISSUE TITLE
按照官网教程 编译出的dist文件里没有project.config.json 文件

### ISSUE THREAD

**Issue by songjingyang** [NervJS/taro-plugin-platform-kwai#13]
taro版本：@tarojs/cli": "3.4.0",
插件：[taro-plugin-platform-kwai](https://github.com/NervJS/taro-plugin-platform-kwai)

**Comment by honlyHuang** [comment]
@songjingyang 项目根目录下，自己添加一个 project.ks.json 文件

**Comment by zhanshihua** [comment]
添加了还是没有 怎么解决的啊  project.ks.json 文件里面的内容是什么
