### ISSUE TITLE
快手小程序的taro watch报错

### ISSUE THREAD

**Issue by bobsam** [NervJS/taro-plugin-platform-kwai#16]
- 执行命令：cross-env BUILD_ENV=development NODE_ENV=development taro build --type kwai --watch

- 然后报错： 

offset_sourcemap_lines_1.default is not a function

(node:16909) UnhandledPromiseRejectionWarning: TypeError: offset_sourcemap_lines_1.default is not a function
    at TaroMiniPlugin.injectCommonStyles (/Users/bob/Documents/workspace/git.nie/a38-client-webfront/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:1189:43)
    at TaroMiniPlugin.<anonymous> (/Users/bob/Documents/workspace/git.nie/a38-client-webfront/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:1006:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bob/Documents/workspace/git.nie/a38-client-webfront/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16909) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

- 环境：

 Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 4.6.3

最近需要基于现有的taro项目迁移到快手~希望尽量回复一下，谢谢！

**Comment by bobsam** [comment]
@Chen-jj 求看看

**Comment by bobsam** [comment]
目前是关闭了enableSourceMap就不会报错了。目测是mini-runner那边对快手的source map支持有问题。

**Comment by AdvancedCat** [comment]
可以提供一个最小可复现DEMO吗？我本地运行没有复现你的问题，也许和具体项目有关系

![91e17da3-d16c-49e7-8412-851a533a0bde](https://user-images.githubusercontent.com/7858761/160974225-3f79f7da-54c4-422c-9a18-f326771a54a4.jpg)

**Comment by bobsam** [comment]
> 可以提供一个最小可复现DEMO吗？我本地运行没有复现你的问题，也许和具体项目有关系
> 
> ![91e17da3-d16c-49e7-8412-851a533a0bde](https://user-images.githubusercontent.com/7858761/160974225-3f79f7da-54c4-422c-9a18-f326771a54a4.jpg)

你开启了enableSourceMap的配置了吗？我发现我打开了就会报错。

**Comment by AdvancedCat** [comment]
> > 可以提供一个最小可复现DEMO吗？我本地运行没有复现你的问题，也许和具体项目有关系
> > ![91e17da3-d16c-49e7-8412-851a533a0bde](https://user-images.githubusercontent.com/7858761/160974225-3f79f7da-54c4-422c-9a18-f326771a54a4.jpg)
> 
> 你开启了enableSourceMap的配置了吗？我发现我打开了就会报错。

设置了 `enableSourceMap` 为 true

**Comment by colinmei00** [comment]
taro通过plugin-platform-kwai转快手小程序后input属性错乱的问题遇到过吗 大佬
