### ISSUE TITLE
基于taro创建的新项目编译快手小程序报错问题

### ISSUE THREAD

**Issue by rainy-cc** [NervJS/taro-plugin-platform-kwai#17]
```
taro : 3.4.6
@tarojs/plugin-platform-kwai: 2.0.0
```
> 编译过程中报错 this.ctx.generateProjectConfig 为undefined, 不清楚为何这个generateProjectConfig方法在插件中没有注入， 其他平台编译都正常注入，只有快手编译该方法异常

**Comment by rainy-cc** [comment]
@Chen-jj  大佬能帮忙看下这个异常么

**Comment by Chen-jj** [comment]
先用 Taro v3.4.4 ，尽快修复的

**Comment by Chen-jj** [comment]
https://github.com/NervJS/taro/pull/11662

**Comment by Chen-jj** [comment]
Taro `v3.4.5`、`v3.4.6` CLI 会触发此问题，`v3.4.7` 解决
