### ISSUE TITLE
cover-view不支持button

### ISSUE THREAD

**Issue by qianlanse** [NervJS/taro-plugin-platform-kwai#18]
https://mp.kuaishou.com/docs/develop/components/view/cover-view.html

**Comment by colinmei00** [comment]
taro通过plugin-platform-kwai转快手小程序后input属性错乱的问题遇到过吗 大佬

**Comment by smackgg** [comment]
@1195846090 建议直接打包成微信小程序，可以直接在快手小程序用

**Comment by colinmei00** [comment]
@smackgg 快手小程序还能支持微信小程序的包吗

**Comment by smackgg** [comment]
你试一下就知道了 @1195846090

**Comment by Chen-jj** [comment]
感谢反馈~下个版本修复
