### ISSUE TITLE
为什么Text标签编译到快手平台后文字展示不出来？

### ISSUE THREAD

**Issue by lunyong** [NervJS/taro-plugin-platform-kwai#19]
如题，查看元素发现两个text标签嵌套在一起，就是没有text的值

**Comment by JiaChaoFei** [comment]
同问，将 text 替换成 view 后可以显示

**Comment by jcf-yu** [comment]
我遇到了同样的问题，将Text替换成View查看后可以显示

**Comment by jcf-yu** [comment]
可以将源码dist/index.js 中的
 case 'text':
 case 'static-text':
          return this.buildFlattenText();
改为
 case 'text':
 case 'static-text':
          return this.buildFlattenView();
暂时替代，等bug 修复后进行升级

**Comment by lunyong** [comment]
> 可以将源码dist/index.js 中的 case 'text': case 'static-text': return this.buildFlattenText(); 改为 case 'text': case 'static-text': return this.buildFlattenView(); 暂时替代，等bug 修复后进行升级

其实直接把这几行代码注释掉就行了，看源码看得很迷，不知道这么做的意义是什么。。。

**Comment by qianlanse** [comment]
我感觉官方不得更新这些插件了

**Comment by colinmei00** [comment]
taro通过plugin-platform-kwai转快手小程序后input属性错乱的问题遇到过吗 大佬

**Comment by Chen-jj** [comment]
最新版本修复
