### ISSUE TITLE
编译成快手 报模版表达式执行错误

### ISSUE THREAD

**Issue by Jo-ko** [NervJS/taro-plugin-platform-kwai#2]
### 描述
用taro init初始化的项目编译成快手时报错
1. 模版表达式执行错误 TypeError: Cannot read property 'cn' of undefined
2. component]: 没找import注册的到组件{{'tmpl_0_' + i.nn}}

![20201224105216](https://user-images.githubusercontent.com/48686166/103056048-db548780-45d6-11eb-91e8-82c04d7bcb44.jpg)

### 环境
tarojs: 3.1.0-beta.4
node: v14.15.1
platform: mac

**Comment by Chen-jj** [comment]
Duplicate of #1
