### ISSUE TITLE
taro 3.5.5 不支持

### ISSUE THREAD

**Issue by lyboy2012** [NervJS/taro-plugin-platform-kwai#20]
直接helloworld 快手项目都无法运行，直接页面空白。

**Comment by lyboy2012** [comment]
快手需要project.config.json 放到编译目录
编译加一条copy解决了
```javascript
copy: {
    patterns: [
      {
        from: 'project.config.json',
        to: `dist/${process.env.TARO_ENV}/project.config.json`,
      },
    ],
    options: {},
  },
```

**Comment by lunyong** [comment]
> 快手需要project.config.json 放到编译目录 编译加一条copy解决了
> 
> ```js
> copy: {
>     patterns: [
>       {
>         from: 'project.config.json',
>         to: `dist/${process.env.TARO_ENV}/project.config.json`,
>       },
>     ],
>     options: {},
>   },
> ```
你是不是把项目配置文件写成 project.kwai.json了？要改成 project.ks.json，和命令里面的那个 kwai 不一样

**Comment by lyboy2012** [comment]
> > 快手需要project.config.json 放到编译目录 编译加一条copy解决了
> > ```js
> > copy: {
> >     patterns: [
> >       {
> >         from: 'project.config.json',
> >         to: `dist/${process.env.TARO_ENV}/project.config.json`,
> >       },
> >     ],
> >     options: {},
> >   },
> > ```
> 
> 你是不是把项目配置文件写成 project.kwai.json了？要改成 project.ks.json，和命令里面的那个 kwai 不一样

<img width="316" alt="image" src="https://user-images.githubusercontent.com/3926781/192726890-e0a37cde-21e1-486a-80ff-3bb6f7a40f50.png">
快手原生也是project.config.json,改成 project.ks.json  ide 也不识别吧？

**Comment by colinmei00** [comment]
taro通过plugin-platform-kwai转快手小程序后input属性错乱的问题遇到过吗 大佬

**Comment by Chen-jj** [comment]
根目录增加 `project.ks.json`，可以直接复制 `project.config.json` 的内容。
