### ISSUE TITLE
flex:1 布局不生效

### ISSUE THREAD

**Issue by lunyong** [NervJS/taro-plugin-platform-kwai#21]
如题，通过这个库编译到快手平台之后，flex:1 是不生效的，但直接写原生是有效果的，非常神奇！
有没有人知道是哪儿的原因呀？
话说，taro还有人维护不？
。。。

**Comment by colinmei00** [comment]
taro通过plugin-platform-kwai转快手小程序后input属性错乱的问题遇到过吗 大佬

**Comment by Chen-jj** [comment]
最新版本是支持 flex 的
