### ISSUE TITLE
不存在编译平台 kwai

### ISSUE THREAD

**Issue by jackxueman** [NervJS/taro-plugin-platform-kwai#23]
throw new Error(`不存在编译平台 ${platform}`);
                  ^
Error: 不存在编译平台 kwai

node:v16.16.0

taro:3.6.2

**Comment by jackxueman** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/11639909/223094187-93121d97-b4f8-42a2-8d21-f722ff14468b.png">

**Comment by qingweiSun** [comment]
请问有解决方案么

**Comment by qingweiSun** [comment]
在index下配置
```
  plugins: [
    '@tarojs/plugin-platform-kwai'
  ],
```
