### ISSUE TITLE
按照官网教程 编译出的dist文件里没有project.config.json 文件，根目录已经添加了 project.ks.json文件 版本6.0.0

### ISSUE THREAD

**Issue by zhanshihua** [NervJS/taro-plugin-platform-kwai#26]

**Comment by Chen-jj** [comment]
![image](https://github.com/NervJS/taro-plugin-platform-kwai/assets/11807297/978bb8e5-fc77-42e1-a482-dcc7a11564f6)

没有复现的，如还有问题可以提供一下 demo
