### ISSUE TITLE
Button 组件不支持onGetPhoneNumber的回调

### ISSUE THREAD

**Issue by Ke-Kou** [NervJS/taro-plugin-platform-kwai#8]
测试发现Button 组件不支持onGetPhoneNumber的回调,原因可能是没有拿到id
![image](https://user-images.githubusercontent.com/89026970/129728049-bfa867f6-672d-4f51-bbfa-8a019bdea082.png)

下面是抖音的
![image](https://user-images.githubusercontent.com/89026970/129728280-66ac3535-847e-4244-98da-d72c0ea30b34.png)

**Comment by smackgg** [comment]
+1
